services:
  - type: web
    name: hackrx-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        fromService:
          type: web
          name: hackrx-api
          property: port
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_API_BASE
        sync: false

